CREATE TABLE Certificados (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    conclusao DATE NOT NULL,
    fk_Cursos_ID INT UNSIGNED,
    fk_Usuarios_ID INT UNSIGNED
);

CREATE TABLE Categorias (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Cursos (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE,
    duracao INT UNSIGNED,
    descricao VARCHAR(255) NOT NULL
);

CREATE TABLE Usuarios (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    estrelas INT UNSIGNED,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha CHAR(32) NOT NULL
);

CREATE TABLE Aulas (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    endereco VARCHAR(255) NOT NULL UNIQUE,
    duracao SMALLINT UNSIGNED NOT NULL,
    fk_Cursos_ID INT UNSIGNED,
    descricao VARCHAR(255) NOT NULL,
    fk_Modulos_ID INT UNSIGNED
);

CREATE TABLE Modulos (
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    numero VARCHAR(5) NOT NULL
);

CREATE TABLE Exercicios (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    fk_Usuarios_ID INT UNSIGNED,
    fk_Cursos_ID INT UNSIGNED,
    nome VARCHAR(255) NOT NULL UNIQUE,
    acertos TINYINT UNSIGNED NOT NULL,
    quant_questoes TINYINT UNSIGNED NOT NULL
);

CREATE TABLE cursos_categorias (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    fk_Cursos_ID INT UNSIGNED,
    fk_Categorias_ID INT UNSIGNED
);

CREATE TABLE usuarios_cursos (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    fk_Usuarios_ID INT UNSIGNED,
    fk_Cursos_ID INT UNSIGNED
);
